### ISSUE TITLE
The PDF generation is not working for Ubuntu 20.04

### ISSUE THREAD

**Issue by otanim** [spatie/temporary-directory#47]
Here is the error log that the system is throwing:
```
Symfony\Component\Process\Exception\ProcessFailedException
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/home/otanim/a-project/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/201306272-0086118001613696745\/index.html","action":"pdf","options":{"path":"\/tmp\/ef398902d431e0d8cf7b0071d43e5331_1_top.pdf","args":["--no-sandbox"],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"emulateMedia":"screen","waitUntil":"networkidle0","width":"2246px","height":"3179px","margin":{"top":"0mm","right":"0mm","bottom":"0mm","left":"0mm"},"printBackground":true}}'" failed. Exit Code: 1(General error) Working directory: /home/otanim/a-project/public Output: ================ Error Output: ================ Error: net::ERR_FILE_NOT_FOUND at file:///tmp/201306272-0086118001613696745/index.html at navigate (/home/otanim/a-project/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async FrameManager.navigateFrame (/home/otanim/a-project/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21) at async Frame.goto (/home/otanim/a-project/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:16) at async Page.goto (/home/otanim/a-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:789:16) at async callChrome (/home/otanim/a-project/vendor/spatie/browsershot/bin/browser.js:171:9)
```

**The problem:**
This issue prevents generating PDF files on Ubuntu OS' 19.10 and in the above versions.

**The solution:**
I've created a new [#46 pull request](https://github.com/spatie/temporary-directory/pull/46#issue-576108329) that will fix this issue.

**Comment by otanim** [comment]
what nonsense is this? it is literally not possible to reopen the issue. the bot is not working as it should be. or rather just disable it.

@freekmurze, may I ask for your attention on this issue?
